export const APP_CONFIG_SETTINGS = {
  APP_TITLE: import.meta.env.VITE_APP_TITLE,
  AUTHOR_URL_LINK: import.meta.env.VITE_AUTHOR_URL_LINK,
  AUTHOR_URL_URI: import.meta.env.VITE_AUTHOR_URL_URI,
  VERSION: import.meta.env.VITE_VERSION,
  PRODUCTS_API_BASE_URL: import.meta.env.VITE_PRODUCTS_API_BASE_URL,
  PRODUCTS_LIST_DEFAULT_LIMIT: import.meta.env.VITE_PRODUCTS_LIST_DEFAULT_LIMIT,
}
